######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 6 17:25:27 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.h device.h enum.h killswitch.h urfkill.h
SOURCES += device.cpp killswitch.cpp main.cpp
QT += dbus
