######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 7 16:20:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += dbus

# Input
HEADERS += client.h device.h enum.h killswitch.h test.h urfkill.h
SOURCES += client.cpp device.cpp killswitch.cpp main.cpp test.cpp
