######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 6 23:03:41 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += dbus

# Input
HEADERS += client.h device.h enum.h killswitch.h urfkill.h
SOURCES += device.cpp killswitch.cpp main.cpp
